language: objective-c
osx_image: xcode8
xcode_workspace: IGRFastFilterView.xcworkspace
xcode_scheme: IGRFastFilterView
sdk: iphonesimulator
sudo: false
env:
  global:
  - LANG=en_US.UTF-8
  - LANGUAGE=en_US.UTF-8
before_install:
  - pod install
