language: objective-c
osx_image: xcode8
xcode_workspace: IGRFastFilterView.xcworkspace
xcode_scheme: IGRFastFilterView
before_install:
    - export LANG=en_US.UTF-8
    - gem install cocoapods
    - pod install