# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

source "https://github.com/CocoaPods/Specs.git"

pod 'IGRFastFilterView', :path => '../'

target 'Demo' do
end

target 'DemoSwift' do
end
